### ISSUE TITLE
error: runlike -p container_name

### ISSUE THREAD

**Issue by MyGodOnLoad** [lavie/runlike#69]
ubuntu@VM-0-12-ubuntu:~$ runlike -p postgres
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/runlike/inspector.py", line 29, in inspect
    output = check_output(
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['docker', 'inspect', 'postgres']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/runlike", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python3.8/site-packages/runlike/runlike.py", line 28, in main
    cli()
  File "/usr/lib/python3/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/runlike/runlike.py", line 23, in cli
    ins.inspect()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/runlike/inspector.py", line 34, in inspect
    if "No such image or container" in e.output:
TypeError: a bytes-like object is required, not 'str'

**Comment by papb** [comment]
This problem also happens to me, regardless of using the `-p` flag. It happens when the container does not exist, or if I'm missing the `--userns=host` flag in my docker run call.

**Comment by lavie** [comment]
Could you please include the steps necessary to recreate the container that caused this?

**Comment by lavie** [comment]
Oh, I think I see what you mean. Is it simply the ugly exception in case of a container that does not exist, or is this something relating to the above `postgres` container?
