### ISSUE TITLE
Crashes on JSON parsing

### ISSUE THREAD

**Issue by fatso83** [lavie/runlike#86]
It does not seem to like the output from my `inspect` command ... Not sure if this is down to the old Docker version (19.03.6) running on the node I captured the output from?

```
$ cat out.txt | docker run --rm -v /var/run/docker.sock:/var/run/docker.sock assaflavie/runlike --stdin
Traceback (most recent call last):
  File "/usr/bin/runlike", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.8/site-packages/runlike/runlike.py", line 37, in main
    cli()
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/runlike/runlike.py", line 31, in cli
    ins.set_facts(raw_json)
  File "/usr/lib/python3.8/site-packages/runlike/inspector.py", line 40, in set_facts
    self.facts = loads(raw_json)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

[out.txt](https://github.com/lavie/runlike/files/7250356/out.txt)

**Comment by lavie** [comment]
Trying adding `-i` to `docker run`

**Comment by fatso83** [comment]
That was it 🙈
