### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by ap88** [lavie/runlike#90]
I have a container running from the [**ownyourbits/nextcloudpi-armhf**](https://hub.docker.com/r/ownyourbits/nextcloudpi-armhf) image. Trying to export with the command _runlike nextcloud_ crashes with the following output:

```
Traceback (most recent call last):
  File "/usr/local/bin/runlike", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/runlike/runlike.py", line 28, in main
    cli()
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/runlike/runlike.py", line 23, in cli
    ins.inspect()
  File "/usr/local/lib/python2.7/dist-packages/runlike/inspector.py", line 32, in inspect
    self.facts = loads(output.decode())
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 9939: ordinal not in range(128)

```

**Comment by Walle123** [comment]
The error comes from the maintainers name.
I fixed it myself by changing 
**output.decode() to output.decode('utf8','strict') in line 32 of inspector.py**
 and additionally you have to change 
 **ins.format.cli() to ins.format.cli().encode(encoding='utf8') in line 24 of runlike.py**
 
 The filepath can be read in the error message

**Comment by lavie** [comment]
@Walle123 thank you. Would you like to submit a patch?

**Comment by Walle123** [comment]
@lavie I am pretty new to github and do not know how to do that

**Comment by lavie** [comment]
I'd be happy to help. 

e.g. if you know you have to change `inspector.py` you can click the edit button and get an editor: https://github.com/lavie/runlike/edit/master/runlike/inspector.py

Then you commit the changes and submit a PR (pull request).

**Comment by Walle123** [comment]
I think i did it right. 
Thank you for your help

**Comment by lavie** [comment]
Appreciated.

The builds did fail, but it's not your fault. There's a known issue with dockerhub. 

I'll fix it soon. Not today though, unfortunately. Very short on time.
